# Generated by Django 6.0 on 2026-01-02 12:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('goals', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='learninggoal',
            name='content_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contenttypes.contenttype'),
        ),
        migrations.AddField(
            model_name='learninggoal',
            name='object_id',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
