# Generated by Django 6.0 on 2025-12-09 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='views',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
