# Generated by Django 6.0 on 2026-01-02 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0002_alter_article_is_approved_alter_book_is_approved_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='estimated_duration',
            field=models.DurationField(blank=True, help_text='Calculated dynamically by the AI.', null=True),
        ),
    ]
