# Generated by Django 6.0 on 2025-12-09 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0002_resource_views'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='is_approved',
            field=models.BooleanField(default=True),
        ),
    ]
