# Generated by Django 6.0 on 2026-01-02 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0003_alter_course_estimated_duration'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='roadmap_json',
            field=models.TextField(blank=True, null=True),
        ),
    ]
