# Generated by Django 6.0 on 2026-01-08 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0005_userlearningstats_moduleprogress'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='ai_generated',
            field=models.BooleanField(default=False, help_text='Whether this course was generated by AI'),
        ),
        migrations.AddField(
            model_name='course',
            name='difficulty_progression',
            field=models.CharField(blank=True, help_text="AI-generated difficulty progression (e.g., 'Beginner to Intermediate')", max_length=100),
        ),
        migrations.AddField(
            model_name='course',
            name='generation_prompt',
            field=models.TextField(blank=True, help_text='The original prompt used to generate this course', null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='course',
            name='popularity_score',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='course',
            name='total_steps',
            field=models.PositiveIntegerField(default=0, help_text='Total number of modules in the course'),
        ),
    ]
